FROM node:18-alpine

WORKDIR /app

# Skip Cypress binary download during image build.
ENV CYPRESS_INSTALL_BINARY=0

COPY package.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
